### ISSUE TITLE
save footer does not appear when updating description on role page

### ISSUE THREAD

**Issue by Wuon** [KonomiAI/Chronicle#202]
steps to reproduce:
- head to role page
- click on admin
- add description
- observe that the save footer does not appear
<img width="1221" alt="Screen Shot 2022-06-01 at 7 55 37 PM" src="https://user-images.githubusercontent.com/20260270/171520182-94a48e1a-dc85-44c3-ab07-7516b507e5dd.png">

expected behaviour:
- save footer should appear when a change is active

**Comment by callmekungfu** [comment]
part of the suite of issues of the page

**Comment by callmekungfu** [comment]
Turns out we never had description for roles; interesting, field will be removed.
