### ISSUE TITLE
Implement CRUD endpoints for roles

### ISSUE THREAD

**Issue by callmekungfu** [KonomiAI/Chronicle#57]
Build crud endpoints for managing roles in the system

```ts
// object id is omitted but necessary
interface Feature {
    title: string;
    read: boolean;
    write: boolean;
}

interface role {
  title: string;
  features: Record<string, Feature>
}
```

### GET

Returns a list of all roles in a tenant.

### POST

Create a new role for a tenant.

### PUT

Update an existing role of a tenant.

Steps to update:

1. fetch the list of features.
2. fetch the existing role details.
3. map role features to available features in system
4. update the existing record by putting a new one over it.

### DELETE

Delete a role from a tenant. Only allowed if the role is not used by any staff members.

**Comment by andrewpratheepan** [comment]
relies on #60
