### ISSUE TITLE
Implement CRUD endpoints for activities

### ISSUE THREAD

**Issue by AnthonyLaiRH** [KonomiAI/Chronicle#69]
```ts
// object id is omitted but necessary

interface IActivity {
    name: string;
    price: number;
    isArchived: boolean;
}
```

### GET

- Returns all activities
- Return an activity by id

### POST

- Create new activity

### PUT

- Update specific activity data by id

### DELETE

- Delete specific activity by id

**Comment by Wuon** [comment]
nice
