### ISSUE TITLE
Update docker compose to support ORM

### ISSUE THREAD

**Issue by callmekungfu** [KonomiAI/Chronicle#81]

**Comment by NguyenPatrick** [comment]
Might not be possible to use Prisma with a local docker instance. Reference link: https://github.com/prisma/prisma/issues/11684.

Any attempt to connect to a local instance using even the prisma mongo db image `prismagraphql/mongo-single-replica:4.4.3-bionic` so far yields in an error. 

Tested Mongo URIs with examples taken from:
- https://v1.prisma.io/docs/1.34/prisma-server/local-prisma-setup-je3i/
- https://github.com/prisma/benching_setup/blob/master/setup_scripts/prisma-server/docker-compose.mongo.yml
- https://github.com/prisma/prisma-examples/blob/ae3abf6e7fd6b6ca956915b1aaaa45bf007bdd0b/databases/mongodb/README.md#3-configure-the-database-connection-url 

All result in errors that ranging from:
```
Error: Database error. error code: unknown, error message: Server selection timeout: No available servers.
```
```
Error: The provided database string is invalid. Unable to parse URL. in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.
```

Short term conclusion: Might not be feasible to setup up a local mongodb container for testing with prisma. Still will try to see if connectivity is possible for the next few hours, but we might have to test using a instance hosted on GCP (which is confirmed to be working)

**Comment by callmekungfu** [comment]
@NguyenPatrick I have a working version of local mongodb, should I PR it for you?

**Comment by NguyenPatrick** [comment]
Yes please

>
